version: "3.7"
services:
  api_service:
    image: "europe-west2-docker.pkg.dev/devops-440713/portfolio/portfolio-app-be"
    restart: always
    ports:
      - "8088:8081"
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/portfolio_app?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb
    
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "europe-west2-docker.pkg.dev/devops-440713/portfolio/mysql"
    restart: always
    ports:
      - 3307:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: portfolio_app
      MYSQL_ROOT_PASSWORD: root

  frontend:
    image: "europe-west2-docker.pkg.dev/devops-440713/portfolio/portfolio-app-fe"
    ports:
      - "3000:80"  # Expose React app on port 3000
    depends_on:
      - api_service  # Ensure the backend service starts before the frontend
    networks:
      - springapimysql-net  #
networks:
  springapimysql-net: